Solves #525 preserves git history on tb image

diff --git a/tb-gcp-tr/landingZone/tb-welcome b/tb-gcp-tr/landingZone/tb-welcome
--- a/tb-gcp-tr/landingZone/tb-welcome
+++ b/tb-gcp-tr/landingZone/tb-welcome
@@ -17,22 +17,22 @@ exec 2> >(tee -ia "/var/log/bootstrap.log" >&2)
 
 date=$(date '+%Y-%m-%d %H:%M:%S')
 echo "Time start: ${date}"
-cd /opt/tb/repo/tb-gcp-tr/landingZone/no-itop
+cd /opt/tb/repo/tb-gcp-tr/landingZone/no-itop || exit
 
 #Retrieve project ID
 PROJECT_ID=$(curl -s "http://metadata.google.internal/computeMetadata/v1/project/project-id" -H "Metadata-Flavor: Google")
 
-echo labels = { > labels.auto.tfvars 
-gcloud projects describe ${PROJECT_ID} --format='value[delimiter=","](labels)' | tr -s "," "\n" | awk -F '=' '{ print $1 "=\"" $2 "\""}' >> labels.auto.tfvars
+echo "labels = {" > labels.auto.tfvars 
+gcloud projects describe "${PROJECT_ID}" --format='value[delimiter=","](labels)' | tr -s "," "\n" | awk -F '=' '{ print $1 "=\"" $2 "\""}' >> labels.auto.tfvars
 echo "}" >> labels.auto.tfvars 
     
 #Retrieve terraform vars
 source input.auto.tfvars
 
 # Create TF state bucket
-buckets=$(sudo gsutil list | grep ${terraform_state_bucket_name})
+buckets=$(sudo gsutil list | grep "${terraform_state_bucket_name}")
 if [ -z "$buckets" ]; then 
-sudo gsutil mb -b on "gs://${terraform_state_bucket_name}/"
+    sudo gsutil mb -b on "gs://${terraform_state_bucket_name}/"
 fi
 
 MAX_ATTEMPTS=10
@@ -42,90 +42,77 @@ export HOME=/root
 #Initialise variables
 SA_NAME="bootstrap-sa"
 SA_EMAIL=${SA_NAME}@${PROJECT_ID}.iam.gserviceaccount.com
-FOLDER_ID=${root_id}
+FOLDER_ID="${root_id}"
 echo "Folder is ${FOLDER_ID}"
-BILLING_ID=${billing_account_id}
+BILLING_ID="${billing_account_id}"
 echo "Billing Id is ${BILLING_ID}"
 
 # The deployment will be done using the bootstrap SA
 echo "Setting [${SA_EMAIL}] as active account"
-sudo gcloud config set account ${SA_EMAIL}
-
-#Make the IAP and Kubectl command scripts executable
-chmod +x /opt/tb/repo/tb-gcp-tr/landingZone/iap-tunnel.sh
-chmod +x /opt/tb/repo/tb-gcp-tr/landingZone/istio-default-install.sh
-chmod +x /opt/tb/repo/tb-gcp-tr/landingZone/add-gcp-fw-for-istio-webhook.sh
-chmod +x /opt/tb/repo/tb-gcp-tr/landingZone/create-private-ingress-gateway.sh
-chmod +x /opt/tb/repo/tb-gcp-tr/landingZone/istio-services_new.sh
-chmod +x /opt/tb/repo/tb-gcp-tr/landingZone/kube.sh
+sudo gcloud config set account "${SA_EMAIL}"
 
 echo "Terraform init"
 # delay to allow nat gateway to be created
 sleep $DELAY_BETWEEN_ATTEMPTS
 apply_failures=0
 while [ $apply_failures -lt $MAX_ATTEMPTS_INIT ]; do
-terraform init -backend-config="bucket=${terraform_state_bucket_name}" -backend-config="prefix=landingZone"
-if [ $? -eq 0 ]; then
-echo "Terraform initialised successfully"
-break
-fi
-if [ $((apply_failures +1)) -eq $MAX_ATTEMPTS_INIT ]; then
-echo "Maximum of $MAX_ATTEMPTS_INIT reached. Moving on..."
-break
-fi
-echo "Terraform init failed."
-apply_failures=$(($apply_failures + 1))
-echo "Retry #$apply_failures starting in $DELAY_BETWEEN_ATTEMPTS seconds."
-sleep $DELAY_BETWEEN_ATTEMPTS
+    if terraform init -backend-config="bucket=${terraform_state_bucket_name}" -backend-config="prefix=landingZone"; then
+        echo "Terraform initialised successfully"
+        break
+    fi
+    if [ $((apply_failures +1)) -eq $MAX_ATTEMPTS_INIT ]; then
+        echo "Maximum of $MAX_ATTEMPTS_INIT reached. Moving on..."
+        break
+    fi
+    echo "Terraform init failed."
+    apply_failures=$((apply_failures + 1))
+    echo "Retry #$apply_failures starting in $DELAY_BETWEEN_ATTEMPTS seconds."
+    sleep $DELAY_BETWEEN_ATTEMPTS
 done
 
 apply_failures=0
 while [ $apply_failures -lt $MAX_ATTEMPTS ]; do
-terraform apply -var-file input.tfvars -auto-approve
-if [ $? -eq 0 ]; then
-/opt/tb/repo/tb-gcp-tr/landingZone/iap-tunnel.sh
-/opt/tb/repo/tb-gcp-tr/landingZone/istio-default-install.sh
-/opt/tb/repo/tb-gcp-tr/landingZone/add-gcp-fw-for-istio-webhook.sh
-/opt/tb/repo/tb-gcp-tr/landingZone/create-private-ingress-gateway.sh
-/opt/tb/repo/tb-gcp-tr/landingZone/istio-services_new.sh
-/opt/tb/repo/tb-gcp-tr/landingZone/kube.sh
-echo "Landing Zone successfully deployed."
-break
-fi
-if [ $((apply_failures +1)) -eq $MAX_ATTEMPTS ]; then
-echo "Maximum of $MAX_ATTEMPTS reached. Moving on..."
-break
-fi
-echo "Landing Zone deployment failed."
-/opt/tb/repo/tb-gcp-tr/landingZone/iap-tunnel.sh
-/opt/tb/repo/tb-gcp-tr/landingZone/istio-default-install.sh
-/opt/tb/repo/tb-gcp-tr/landingZone/add-gcp-fw-for-istio-webhook.sh
-/opt/tb/repo/tb-gcp-tr/landingZone/create-private-ingress-gateway.sh
-/opt/tb/repo/tb-gcp-tr/landingZone/istio-services_new.sh
-/opt/tb/repo/tb-gcp-tr/landingZone/kube.sh
-apply_failures=$((apply_failures + 1))
-echo "Retry #$apply_failures starting in $DELAY_BETWEEN_ATTEMPTS seconds."
-sleep $DELAY_BETWEEN_ATTEMPTS
+    if terraform apply -var-file input.tfvars -auto-approve; then
+        /opt/tb/repo/tb-gcp-tr/landingZone/iap-tunnel.sh
+        /opt/tb/repo/tb-gcp-tr/landingZone/istio-default-install.sh
+        /opt/tb/repo/tb-gcp-tr/landingZone/add-gcp-fw-for-istio-webhook.sh
+        /opt/tb/repo/tb-gcp-tr/landingZone/create-private-ingress-gateway.sh
+        /opt/tb/repo/tb-gcp-tr/landingZone/istio-services_new.sh
+        /opt/tb/repo/tb-gcp-tr/landingZone/kube.sh
+        echo "Landing Zone successfully deployed."
+        break
+    fi
+    if [ $((apply_failures +1)) -eq $MAX_ATTEMPTS ]; then
+        echo "Maximum of $MAX_ATTEMPTS reached. Moving on..."
+        break
+    fi
+        echo "Landing Zone deployment failed."
+        apply_failures=$((apply_failures + 1))
+        echo "Retry #$apply_failures starting in $DELAY_BETWEEN_ATTEMPTS seconds."
+        sleep $DELAY_BETWEEN_ATTEMPTS
 done
 
 # Set versioning on for tf state bucket.
 sudo gsutil versioning set on "gs://${terraform_state_bucket_name}/"
 
 # Commit current TB terraform code to GCR
-cd /tmp
-# Check for repo existence
-RepoList=$(sudo gcloud source repos list | grep tb-terraform-code)
-if [ -z "$RepoList" ]; then
-sudo gcloud source repos create tb-terraform-code
+if ! gcloud source repos list | grep -q tb-terraform-code; then
+    gcloud source repos create tb-terraform-code
 fi
 
-sudo gcloud source repos clone tb-terraform-code
-cd /tmp/tb-terraform-code
-rsync -a /opt/tb/repo/ .
-git init
-git add .
-git commit -m "Landing zone terraform script"
-git push -u origin master
+git config --global credential.'https://source.developers.google.com'.helper gcloud.sh
+
+if ! git remote -v | grep -q upstream; then
+    git remote rename origin upstream
+fi
+
+if ! git remote -v | grep -q origin; then
+    git remote add origin "$(gcloud source repos describe tb-terraform-code --format='value(url)')"
+fi
+
+git add -A
+git commit -m "Deployment config & generated scripts"
+git push -u origin HEAD:master
 
 date=$(date '+%Y-%m-%d %H:%M:%S')
 echo "Time end: ${date}"
