Moved folder

diff --git a/tb-gcp-tr/landingZone/tb-welcome b/tb-gcp-tr/landingZone/tb-welcome
--- a/tb-gcp-tr/landingZone/tb-welcome
+++ b/tb-gcp-tr/landingZone/tb-welcome
@@ -21,14 +21,13 @@ function create_configuration {
   echo "1. Permissions of the Service Account:"
   echo "  - at the project level [${PROJECT_ID}]"
   echo "    - compute.admin"
-  echo "    - storage.admin"
   echo "  - at the folder level [${FOLDER_ID}]"
   echo "    - resourcemanager.folderAdmin"
   echo "    - resourcemanager.projectCreator"
   echo "    - resourcemanager.projectDeleter"
   echo "    - compute.networkAdmin"
   echo "    - compute.xpnAdmin"
-#  echo "    - owner"
+  echo "    - owner"
   echo "  - at the billing account level [${BILLING_ID}]"
   echo "    - billing.admin"
   echo "2.Activation of the following API's:"
@@ -67,7 +66,6 @@ function create_configuration {
   #Add permissions at the project level
   echo "Adding permissions at the project level... "
   gcloud projects add-iam-policy-binding "${PROJECT_ID}" --member=serviceAccount:"${SA_EMAIL}" --role=roles/compute.instanceAdmin.v1 --format=none
-#  gcloud projects add-iam-policy-binding "${PROJECT_ID}" --member=serviceAccount:"${SA_EMAIL}" --role=roles/storage.admin --format=none
 
   # Add permissions at the folder level
   echo "Adding permissions at the folder level..."
@@ -212,6 +210,102 @@ function init() {
   fi
 }
 
+
+
+
+
+
+function create_bootstrap2() {
+
+PROJECT_ID=$(curl -s "http://metadata.google.internal/computeMetadata/v1/project/project-id" -H "Metadata-Flavor: Google")
+#Initialise variables
+SA_NAME="bootstrap-tb-sa"
+SA_EMAIL=${SA_NAME}@${PROJECT_ID}.iam.gserviceaccount.com
+
+VM_NAME="$(curl -s "http://metadata.google.internal/computeMetadata/v1/instance/name" -H "Metadata-Flavor: Google")"
+# strip the prefix from the ouptut (e.g., projects/318521105370/zones/europe-west2-a)
+ZONE=$(curl -s "http://metadata.google.internal/computeMetadata/v1/instance/zone" -H "Metadata-Flavor: Google" | awk -F/ '{print $NF}')
+REGION=${ZONE::-2}
+NETWORK=$(gcloud compute instances describe ${VM_NAME} --zone europe-west2-a | grep network: -w | awk -F/ '{print $NF}')
+SUBNET=$(gcloud compute instances describe ${VM_NAME} --zone europe-west2-a | grep subnetwork: -w | awk -F/ '{print $NF}')
+
+echo $VM_NAME
+echo $ZONE
+echo $NETWORK
+echo $SUBNET
+echo $REGION
+
+gcloud compute instances create ${VM_NAME}5 --service-account=${SA_EMAIL} \
+--zone=${ZONE} --no-address --network=${NETWORK} --subnet=${SUBNET} \
+--image=tranquility-base-bootstrap-issue-171 --image-project=tb-marketplace-dev \
+--scopes cloud-platform --tags=iap,no-ip,tbase-test-1-deployment \
+--metadata startup-script='#!/bin/bash
+exec >> /var/log/bootstrap.log 2>&1
+MAX_ATTEMPTS=10
+MAX_ATTEMPTS_INIT=3
+DELAY_BETWEEN_ATTEMPTS=60
+
+export HOME=/root
+echo "Create Landing Zone Terraform Variable File"
+cd /opt/tb/repo/tb-gcp-tr/landingZone/no-itop
+
+cat <<EOF > input.auto.tfvars
+region="'${region}'"
+region_zone="'${region_zone}'"
+billing_account_id="'${BILLING_ID}'"
+root_id="'${FOLDER_ID}'"
+root_is_org="'${root_is_org}'"
+tb_discriminator="'${tb_discriminator}'"
+terraform_state_bucket_name="'${terraform_state_bucket_name}'"
+clusters_master_whitelist_ip="'${clusters_master_whitelist_ip}'"
+EOF
+
+# Create TF state bucket
+gsutil mb gs://'${terraform_state_bucket_name}'/
+
+echo "Set Input Vars"
+source input.auto.tfvars
+
+echo "Terraform init"
+# delay to allow nat gateway to be created
+sleep $DELAY_BETWEEN_ATTEMPTS
+apply_failures=0
+while [ $apply_failures -lt $MAX_ATTEMPTS_INIT ]; do
+ terraform init -backend-config="bucket=${terraform_state_bucket_name}" -backend-config="prefix=landingZone"
+  if [ $? -eq 0 ]; then
+  echo "Terraform initialised successfully"
+ break
+  fi
+  if [ $((apply_failures +1)) -eq $MAX_ATTEMPTS_INIT ]; then
+  echo "Maximum of $MAX_ATTEMPTS_INIT reached. Aborting..."
+  exit 1;
+   break
+ fi
+ echo "Terraform init failed."
+ apply_failures=$(($apply_failures + 1))
+ echo "Retry #$apply_failures starting in $DELAY_BETWEEN_ATTEMPTS seconds."
+ sleep $DELAY_BETWEEN_ATTEMPTS
+done
+
+apply_failures=0
+while [ $apply_failures -lt $MAX_ATTEMPTS ]; do
+ terraform apply -var-file input.tfvars -auto-approve
+ if [ $? -eq 0 ]; then
+ echo "Landing Zone successfully deployed."
+   break
+  fi
+  if [ $((apply_failures +1)) -eq $MAX_ATTEMPTS ]; then
+  echo "Maximum of $MAX_ATTEMPTS reached.  Aborting..."
+    exit 1;
+  break
+ fi
+ echo "Landing Zone deployment failed."
+ apply_failures=$(($apply_failures + 1))
+ echo "Retry #$apply_failures starting in $DELAY_BETWEEN_ATTEMPTS seconds."
+ sleep $DELAY_BETWEEN_ATTEMPTS
+done'
+}
+
 #Retrieve terraform vars
 cd /opt/tb/repo/tb-gcp-tr/landingZone/no-itop
 source input.auto.tfvars
@@ -234,6 +328,9 @@ then
 elif [ "$argument" == "config" ]
 then
   create_configuration
+elif [ "$argument" == "vm" ]
+then
+  create_bootstrap2
 else
   print_help
 fi
