Added bootstrap script to terraform server with paramatized env variables

diff --git a/tb-gcp-tr/bootstrap/GDM/config.yaml b/tb-gcp-tr/bootstrap/GDM/config.yaml
--- a/tb-gcp-tr/bootstrap/GDM/config.yaml
+++ b/tb-gcp-tr/bootstrap/GDM/config.yaml
@@ -28,6 +28,8 @@ resources:
       concurrent_api_activation: False
 
 
+
+
       # Change the following to your organization's billing account
       billing-account-name: billingAccounts/[BILLING_ACCOUNT_ID]
 
@@ -68,7 +70,57 @@ resources:
 
       vm:
         - my-vm-1
+      startup-script: |
+        #!/bin/bash
+        exec >> /var/log/bootstrap.log 2>&1
 
+        MAX_ATTEMPTS=10
+        DELAY_BETWEEN_ATTEMPTS=60
+
+        export HOME=/root
+        apt-get -y install git
+        apt-get -y install kubectl
+
+        cd /opt/tb/repo/tb-gcp-tr/landingZone/
+        cat <<EOF > input.auto.tfvars
+        clusters_master_whitelist_ip = "${clusters_master_whitelist_ip}"
+        region = "${region}"
+        region_zone = "${region_zone}"
+        root_id = "${root_id}"
+        root_is_org = "${root_is_org}"
+        billing_account_id = "${billing_account_id}"
+        tb_discriminator = "${tb_discriminator}"
+        terraform_state_bucket_name = "${terraform_state_bucket_name}"
+        EOF
+        terraform init -backend-config="bucket=${terraform_state_bucket_name}" -backend-config="prefix=landingZone"
+
+        apply_failures=0
+        while [ $apply_failures -lt $MAX_ATTEMPTS ]; do
+          terraform apply -var-file input.tfvars -auto-approve
+          if [ $? -eq 0 ]; then
+            echo "Landing Zone successfully deployed."
+            break
+          fi
+          if [ $((apply_failures +1)) -eq $MAX_ATTEMPTS ]; then
+            echo "Maximum of $MAX_ATTEMPTS reached. Moving on..."
+            break
+          fi
+          echo "Landing Zone deployment failed."
+          apply_failures=$(($apply_failures + 1))
+          echo "Retry #$apply_failures starting in $DELAY_BETWEEN_ATTEMPTS seconds."
+          sleep $DELAY_BETWEEN_ATTEMPTS
+        done
+
+        # Commit current TB terraform code to GCR
+        cd /tmp
+        gcloud source repos create tb-terraform-code
+        gcloud source repos clone tb-terraform-code
+        cd /tmp/tb-terraform-code
+        rsync -a /opt/tb/repo/ .
+        git init
+        git add .
+        git commit -m "Landing zone terraform script"
+        git push -u origin master
       startupScript: |
         #!/bin/bash
         echo 1 > /proc/sys/net/ipv4/ip_forward
